import { useEffect, useMemo, useState } from 'react';
import logo from './assets/fynvo-logo.svg';
import mark from './assets/fynvo-mark.svg';
import './styles.css';

const api = (path, options = {}) => fetch(`api${path}`, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
const today = new Date().toISOString().slice(0, 10);
const nav = ['Overview', 'Accounts', 'Transactions', 'Income', 'Recurring Expenses', 'Bills', 'Planned Spending', 'Categories', 'Budgeting', 'CSV Import', 'Import History', 'Review Queue', 'Cash Flow', 'Calendar'];
const money = (value) => value === null || value === undefined || value === '' ? 'Pending' : new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD' }).format(Number(value || 0));
const dateLabel = (value) => value ? new Intl.DateTimeFormat('en-AU', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) : 'Pending';
const amountClass = (value) => Number(value || 0) >= 0 ? 'positive' : 'negative';
const Field = ({ label, children, ...props }) => <label className="field"><span>{label}</span>{children || <input {...props}/>}</label>;
const Badge = ({ children, tone = '' }) => <span className={`badge ${tone}`}>{children}</span>;
const Empty = ({ title, children }) => <div className="empty"><strong>{title}</strong><p>{children}</p></div>;
const toDateInput = (value) => value ? String(value).slice(0, 10) : '';

function normaliseRecord(type, row) {
  if (!row) return {};
  if (type === 'accounts') return { name: row.name || '', account_type: row.account_type || 'transaction', institution: row.institution || '', opening_balance: row.opening_balance || '0.00', description: row.description || '', account_suffix: row.account_suffix || '', icon: row.icon || '', color: row.color || '' };
  if (type === 'transactions') return { account_id: row.account_id || '', date: toDateInput(row.date || row.transaction_date), amount: row.amount || '', transaction_type: row.transaction_type || 'expense', description: row.description || '', merchant: row.merchant || '', category: row.category || '', notes: row.notes || '', status: row.status || 'cleared' };
  if (type === 'income') return { name: row.name || '', amount: row.amount || '', frequency: row.frequency || 'monthly', next_payment_date: toDateInput(row.next_payment_date), destination_account_id: row.destination_account_id || '', payer: row.payer || '', category: row.category || '', is_active: row.is_active ?? true, notes: row.notes || '', effective_from: '' };
  if (type === 'recurring') return { name: row.name || '', amount: row.amount || '', frequency: row.frequency || 'monthly', next_due_date: toDateInput(row.next_due_date), account_id: row.account_id || '', source_account_text: row.source_account_text || '', category: row.category || '', expense_type: row.expense_type || '', is_active: row.is_active ?? true, variable_amount: row.variable_amount ?? false, direct_debit: row.direct_debit ?? false, notes: row.notes || '', effective_from: '' };
  if (type === 'bills') return { name: row.name || '', provider: row.provider || '', bill_type: row.bill_type || '', priority: row.priority || 'normal', amount: row.amount || '', due_date: toDateInput(row.due_date), account_id: row.account_id || '', paid_through_date: toDateInput(row.paid_through_date), status: row.status || '', notes: row.notes || '', recurring_expense_id: row.recurring_expense_id || '' };
  if (type === 'planned') return { name: row.name || '', description: row.description || '', estimated_amount: row.estimated_amount || '', planned_date: toDateInput(row.planned_date), category: row.category || '', account_id: row.account_id || '', merchant: row.merchant || '', priority: row.priority || 'medium', status: row.status || 'wishlist', include_in_forecast: row.include_in_forecast ?? true, notes: row.notes || '' };
  if (type === 'categories') return { name: row.name || '', parent_id: row.parent_id || '', icon: row.icon || '', color: row.color || '', category_type: row.category_type || 'expense', budget_relationship: row.budget_relationship || 'independent', is_active: row.is_active ?? true, notes: row.notes || '' };
  if (type === 'budgets') return { name: row.name || '', category_id: row.category_id || '', category_name: row.category_name || '', direction: row.direction || 'expense', period: row.period || 'monthly', amount: row.amount || '', allocation_strategy: row.allocation_strategy || 'spend_during_period', relationship_mode: row.relationship_mode || 'independent', anchor_date: toDateInput(row.anchor_date) || today, start_date: toDateInput(row.start_date) || today, end_date: toDateInput(row.end_date), rollover_enabled: row.rollover_enabled ?? false, negative_rollover_enabled: row.negative_rollover_enabled ?? false, is_active: row.is_active ?? true, notes: row.notes || '', effective_from: '' };
  return { ...row };
}

function endpointFor(type, id) {
  return ({ accounts: `/accounts/${id}`, transactions: `/transactions/${id}`, income: `/income/${id}`, recurring: `/recurring-expenses/${id}`, bills: `/bills/${id}`, planned: `/planned-spending/${id}`, categories: `/categories/${id}`, budgets: `/budgets/${id}` })[type];
}

export default function App() {
  const [auth, setAuth] = useState(null);
  const [active, setActive] = useState(localStorage.getItem('fynvo.view') || 'Overview');
  const [form, setForm] = useState({ username: '', display_name: '', password: '' });
  const [data, setData] = useState({ accounts: [], transactions: [], income: [], recurring: [], bills: [], planned: [], categories: [], budgets: [], imports: [], review: [], budgetAnalysis: null, forecast: null });
  const [error, setError] = useState('');
  const [edit, setEdit] = useState(null);
  const [quick, setQuick] = useState(null);
  const [importState, setImportState] = useState({ filename: '', account_id: '', csv_text: '', source_name: 'Australian bank CSV', mapping: { date: 'Date', description: 'Description', debit: 'Debit', credit: 'Credit', amount: 'Amount' }, preview: null });

  async function loadAuth() { const res = await api('/auth/state'); setAuth(await res.json()); }
  async function j(path) { const res = await api(path); return res.ok ? await res.json() : null; }
  async function loadData() {
    const [overview, accounts, transactions, income, recurring, bills, planned, categories, budgets, imports, review, budgetAnalysis, forecast] = await Promise.all([
      j('/dashboard/overview'), j('/accounts'), j('/transactions'), j('/income'), j('/recurring-expenses'), j('/bills'), j('/planned-spending'), j('/categories'), j('/budgets'), j('/imports/history'), j('/reconciliation/review-queue'), j('/budgets/analysis'), j('/forecast?mode=expected&horizon=30d'),
    ]);
    setData({ overview, accounts: accounts || [], transactions: transactions || [], income: income || [], recurring: recurring || [], bills: bills || [], planned: planned || [], categories: categories || [], budgets: budgets || [], imports: imports || [], review: review || [], budgetAnalysis, forecast });
  }
  useEffect(() => { loadAuth(); }, []);
  useEffect(() => { if (auth?.authenticated) loadData(); }, [auth?.authenticated]);
  useEffect(() => { localStorage.setItem('fynvo.view', active); }, [active]);

  async function submitAuth(e) { e.preventDefault(); setError(''); const payload = auth?.setup_required ? { username: form.username, display_name: form.display_name || form.username, password: form.password } : { username: form.username, password: form.password }; const res = await api(auth?.setup_required ? '/auth/setup' : '/auth/login', { method: 'POST', body: JSON.stringify(payload) }); if (res.ok) await loadAuth(); else setError('Sign-in failed.'); }
  async function logout() { await api('/auth/logout', { method: 'POST' }); setAuth({ authenticated: false, setup_required: false, user: null }); }
  async function saveEdit(e) { e.preventDefault(); setError(''); const res = await api(endpointFor(edit.type, edit.row.id), { method: 'PUT', body: JSON.stringify(edit.values) }); if (!res.ok) { setError(`Could not save ${edit.label}. Check the fields and try again.`); return; } setEdit(null); await loadData(); }
  async function createRecord(type, values) { const path = ({ accounts: '/accounts', transactions: '/transactions', income: '/income', recurring: '/recurring-expenses', bills: '/bills', planned: '/planned-spending', categories: '/categories', budgets: '/budgets' })[type]; const res = await api(path, { method: 'POST', body: JSON.stringify(values) }); if (res.ok) { setQuick(null); await loadData(); } else setError('Create failed. Check required fields.'); }
  async function previewImport(e) { e.preventDefault(); const res = await api('/imports/preview', { method: 'POST', body: JSON.stringify(importState) }); if (res.ok) setImportState({ ...importState, preview: await res.json() }); else setError('CSV preview failed. Check the account, headers and mapping.'); }
  async function commitImport() { const res = await api('/imports/commit', { method: 'POST', body: JSON.stringify(importState) }); if (res.ok) { setImportState({ ...importState, preview: await res.json() }); await loadData(); } else setError('CSV import failed. Review invalid rows and duplicates.'); }
  async function acceptMatch(id) { const res = await api(`/reconciliation/${id}/accept`, { method: 'POST' }); if (res.ok) await loadData(); else setError('Could not accept match.'); }

  if (!auth) return <main className="login"><div className="login-card"><img className="login-logo" src={logo} alt="Fynvo"/><p>Loading...</p></div></main>;
  if (!auth.authenticated) return <main className="login"><form className="login-card" onSubmit={submitAuth}><img className="login-logo" src={logo} alt="Fynvo"/><p>Know what's coming.</p>{auth.setup_required && <p className="notice">Create the first administrator account.</p>}<Field label="Username" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })}/>{auth.setup_required && <Field label="Display name" value={form.display_name} onChange={(e) => setForm({ ...form, display_name: e.target.value })}/>}<Field label="Password" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })}/>{error && <p className="error">{error}</p>}<button className="primary">{auth.setup_required ? 'Create account' : 'Sign in'}</button></form></main>;

  return <div className="shell"><aside className="sidebar"><div className="brand"><img src={mark} alt=""/><div><strong>Fynvo</strong><small>Know what's coming.</small></div></div><nav>{nav.map((item) => <button key={item} className={active === item ? 'active' : ''} onClick={() => setActive(item)}>{item}</button>)}</nav><div className="user-card"><span>SP</span><div><strong>{auth.user?.display_name}</strong><small>Household</small></div></div></aside><main className="content"><header className="header"><div><p className="eyebrow">Fynvo v0.9.0</p><h1>{active}</h1><p>Maintain existing records and reconcile actual bank transactions.</p></div><div className="header-actions"><button className="primary ghost" onClick={() => setQuick({ type: 'transactions', values: { date: today, amount: '', transaction_type: 'expense', description: '', account_id: data.accounts[0]?.id || '', category: '' } })}>+ Quick Add</button><button onClick={logout}>Logout</button></div></header>{error && <p className="error banner">{error}</p>}
    {active === 'Overview' && <Overview data={data} setActive={setActive}/>} 
    {active === 'Cash Flow' && <ForecastPanel forecast={data.forecast}/>} 
    {active === 'Calendar' && <ForecastPanel forecast={data.forecast}/>} 
    {active === 'CSV Import' && <CsvImport state={importState} setState={setImportState} accounts={data.accounts} previewImport={previewImport} commitImport={commitImport}/>} 
    {active === 'Import History' && <ImportHistory rows={data.imports}/>} 
    {active === 'Review Queue' && <ReviewQueue rows={data.review} acceptMatch={acceptMatch}/>} 
    {active === 'Budgeting' && <Budgeting budgets={data.budgets} analysis={data.budgetAnalysis} categories={data.categories} onEdit={(row) => setEdit({ type: 'budgets', label: 'Budget', row, values: normaliseRecord('budgets', row) })}/>} 
    {['Accounts','Transactions','Income','Recurring Expenses','Bills','Planned Spending','Categories'].includes(active) && <RecordTable active={active} data={data} onEdit={setEdit}/>} 
  </main>{edit && <EditModal edit={edit} setEdit={setEdit} onSubmit={saveEdit} data={data}/>} {quick && <EditModal edit={{ ...quick, row: { id: null }, label: 'New transaction' }} setEdit={setQuick} onSubmit={(e) => { e.preventDefault(); createRecord(quick.type, quick.values); }} data={data}/>}</div>;
}

function Overview({ data, setActive }) {
  const s = data.overview?.summary || {};
  return <><section className="kpi-grid"><Kpi label="Available cash" value={s.available_cash}/><Kpi label="Planned Spending" value={s.planned_spending}/><Kpi label="Projected balance" value={s.projected_balance}/><Kpi label="Bills due" value={s.bills_due_count}/></section><section className="dashboard-grid"><article className="panel"><h2>Record editing is active</h2><p>Open any major financial list and use the Edit action. Edits persist after refresh and update dependent views through the same APIs.</p><button className="primary" onClick={() => setActive('Bills')}>Edit bills →</button></article><article className="panel"><h2>CSV Import & Reconciliation</h2><p>Upload an Australian bank CSV, map columns, preview duplicates and match transactions to Bills, Recurring Expenses or Planned Spending.</p><button className="primary ghost" onClick={() => setActive('CSV Import')}>Import CSV →</button></article><article className="panel"><h2>Budget Analysis</h2>{data.budgetAnalysis?.summary ? <><SummaryRow label="Base budget" value={data.budgetAnalysis.summary.base_budget}/><SummaryRow label="Actual spending" value={data.budgetAnalysis.summary.actual_spending}/><SummaryRow label="Forecast spending" value={data.budgetAnalysis.summary.forecast_spending}/></> : <Empty title="No budget analysis yet">Create budgets to see Budget vs Actual vs Forecast.</Empty>}</article></section></>;
}
function Kpi({ label, value }) { return <article className="kpi"><span className="kpi-icon">◆</span><div><span>{label}</span><strong>{typeof value === 'number' ? value : money(value)}</strong></div></article>; }
function SummaryRow({ label, value }) { return <div className="summary-row"><span>{label}</span><strong className={amountClass(value)}>{money(value)}</strong></div>; }

function RecordTable({ active, data, onEdit }) {
  const cfg = {
    Accounts: ['accounts', data.accounts, 'Account'], Transactions: ['transactions', data.transactions, 'Transaction'], Income: ['income', data.income, 'Income'], 'Recurring Expenses': ['recurring', data.recurring, 'Recurring Expense'], Bills: ['bills', data.bills, 'Bill'], 'Planned Spending': ['planned', data.planned, 'Planned Spending'], Categories: ['categories', data.categories, 'Category'],
  }[active];
  const [type, rows, label] = cfg;
  return <section className="panel"><div className="panel-head"><div><h2>{active}</h2><p className="muted">Each row has an Edit action. Sorting and saved-view foundations remain untouched.</p></div><button className="primary ghost" onClick={() => onEdit({ type, label: `New ${label}`, row: { id: null }, values: normaliseRecord(type, {}) })}>+ Add</button></div>{rows.length ? <div className="table"><div className="thead"><span>Date</span><span>Name</span><span>Amount</span><span>Status</span><span>Actions</span></div>{rows.map((r) => <div className="tr five" key={r.id}><span>{r.date || r.transaction_date || r.next_due_date || r.next_payment_date || r.due_date || r.planned_date || '—'}</span><span>{r.name || r.description || r.path}<small>{r.category_path || r.category || r.bill_type || r.account_type || r.provider || ''}</small></span><strong className={amountClass(r.amount || r.estimated_amount || r.current_balance)}>{money(r.amount || r.estimated_amount || r.current_balance)}</strong><span><Badge>{r.status || r.frequency || (r.is_active === false ? 'Inactive' : 'Active')}</Badge></span><span><button onClick={() => onEdit({ type, label, row: r, values: normaliseRecord(type, r) })}>Edit</button></span></div>)}</div> : <Empty title={`No ${active.toLowerCase()} yet`}>Create the first record using Add or Quick Add.</Empty>}</section>;
}

function Budgeting({ budgets, analysis, categories, onEdit }) { return <><section className="kpi-grid"><Kpi label="Base Budget" value={analysis?.summary?.base_budget}/><Kpi label="Actual" value={analysis?.summary?.actual_spending}/><Kpi label="Forecast" value={analysis?.summary?.forecast_spending}/><Kpi label="Variance" value={analysis?.summary?.forecast_surplus_deficit}/></section><section className="panel"><div className="panel-head"><h2>Budgets</h2><button className="primary ghost" onClick={() => onEdit({ id: null, name: '', category_id: categories[0]?.id || '', period: 'monthly', amount: '', anchor_date: today, start_date: today })}>+ Create Budget</button></div>{budgets.length ? <div className="table"><div className="thead"><span>Category</span><span>Period</span><span>Budget</span><span>Status</span><span>Actions</span></div>{budgets.map((b) => <div className="tr five" key={b.id}><span>{b.category_path || b.category_name || b.name}</span><span>{b.period}</span><strong>{money(b.amount)}</strong><Badge>{b.relationship_mode}</Badge><span><button onClick={() => onEdit(b)}>Edit</button></span></div>)}</div> : <Empty title="No budgets yet">Create a budget to activate Budget vs Actual analysis.</Empty>}</section><section className="panel"><h2>Unbudgeted Categories</h2>{analysis?.unbudgeted_categories?.length ? analysis.unbudgeted_categories.map((u) => <div className="mini-row" key={u.category}><span>{u.category}<small>{u.transaction_count} transactions</small></span><strong>{money(u.actual)}</strong></div>) : <Empty title="No unbudgeted categories found">Imported and manual transactions will appear here if they have activity but no budget.</Empty>}</section></>; }

function EditModal({ edit, setEdit, onSubmit, data }) {
  const v = edit.values;
  const set = (patch) => setEdit({ ...edit, values: { ...v, ...patch } });
  const fields = Object.keys(v).filter((k) => !['id'].includes(k));
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><form className="modal" onSubmit={onSubmit}><button type="button" className="close" onClick={() => setEdit(null)}>×</button><h2>{edit.row?.id ? `Edit ${edit.label}` : edit.label}</h2><p className="muted">For amount or recurrence changes, use Effective from to treat it as a future-dated change. Leave it blank to correct the existing record.</p>{fields.map((key) => <DynamicField key={key} name={key} value={v[key]} set={set} data={data}/>) }<div className="modal-actions"><button className="primary">Save</button><button type="button" onClick={() => setEdit(null)}>Cancel</button></div></form></div>;
}
function DynamicField({ name, value, set, data }) {
  const label = name.replaceAll('_', ' ');
  if (['account_id','destination_account_id'].includes(name)) return <Field label={label}><select value={value || ''} onChange={(e) => set({ [name]: e.target.value ? Number(e.target.value) : null })}><option value="">None</option>{data.accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></Field>;
  if (name === 'category_id' || name === 'parent_id') return <Field label={label}><select value={value || ''} onChange={(e) => set({ [name]: e.target.value ? Number(e.target.value) : null })}><option value="">None</option>{data.categories.map((c) => <option key={c.id} value={c.id}>{c.path || c.name}</option>)}</select></Field>;
  if (typeof value === 'boolean') return <label className="check"><input type="checkbox" checked={!!value} onChange={(e) => set({ [name]: e.target.checked })}/>{label}</label>;
  if (name.includes('date') || name === 'effective_from') return <Field label={label} type="date" value={value || ''} onChange={(e) => set({ [name]: e.target.value })}/>;
  if (['frequency','period'].includes(name)) return <Field label={label}><select value={value || ''} onChange={(e) => set({ [name]: e.target.value })}><option value="weekly">Weekly</option><option value="fortnightly">Fortnightly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual">Annual</option><option value="yearly">Yearly</option><option value="one_off">One off</option></select></Field>;
  if (['priority'].includes(name)) return <Field label={label}><select value={value || ''} onChange={(e) => set({ [name]: e.target.value })}><option value="low">Low</option><option value="normal">Normal</option><option value="medium">Medium</option><option value="high">High</option></select></Field>;
  if (['status'].includes(name)) return <Field label={label}><select value={value || ''} onChange={(e) => set({ [name]: e.target.value })}><option value="">Auto</option><option value="wishlist">Wishlist</option><option value="planned">Planned</option><option value="committed">Committed</option><option value="purchased">Purchased</option><option value="paid">Paid</option><option value="resolved">Resolved</option><option value="cleared">Cleared</option></select></Field>;
  return <Field label={label} value={value || ''} onChange={(e) => set({ [name]: e.target.value })}/>;
}

function CsvImport({ state, setState, accounts, previewImport, commitImport }) {
  const setMapping = (key, value) => setState({ ...state, mapping: { ...state.mapping, [key]: value } });
  return <section className="panel"><h2>CSV Bank Transaction Import</h2><p className="muted">Upload, map columns, preview, detect duplicates, reconcile against bills, recurring expenses and Planned Spending, then import as Actual transactions.</p><form onSubmit={previewImport} className="form-grid"><Field label="Destination account"><select value={state.account_id} onChange={(e) => setState({ ...state, account_id: e.target.value })}><option value="">Select account</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="File name" value={state.filename} onChange={(e) => setState({ ...state, filename: e.target.value })}/><label className="field"><span>CSV file</span><input type="file" accept=".csv,text/csv" onChange={async (e) => { const file = e.target.files?.[0]; if (file) setState({ ...state, filename: file.name, csv_text: await file.text() }); }}/></label><label className="field wide"><span>CSV content</span><textarea value={state.csv_text} onChange={(e) => setState({ ...state, csv_text: e.target.value })} rows="8" placeholder="Date,Description,Debit,Credit\n22/08/2026,POWERSHOP,278.64,"/></label>{['date','description','merchant','debit','credit','amount'].map((k) => <Field key={k} label={`Map ${k}`} value={state.mapping[k] || ''} onChange={(e) => setMapping(k, e.target.value)}/>) }<button className="primary">Preview import</button></form>{state.preview?.rows && <ImportPreview preview={state.preview} commitImport={commitImport}/>}</section>;
}
function ImportPreview({ preview, commitImport }) { return <section className="panel inset"><div className="panel-head"><div><h2>Import Preview</h2><p>{preview.summary?.row_count} rows · {preview.summary?.duplicates} duplicates · {preview.summary?.matches} suggested matches · {preview.summary?.invalid} invalid</p></div><button className="primary" onClick={commitImport}>Confirm import</button></div><div className="table"><div className="thead"><span>Date</span><span>Description</span><span>Amount</span><span>Status</span><span>Suggestion</span></div>{preview.rows.map((r) => <div className="tr five" key={r.row_number}><span>{r.date || 'Invalid'}</span><span>{r.description}<small>{r.category || r.errors?.join(', ')}</small></span><strong>{money(r.amount)}</strong><Badge tone={r.status?.includes('duplicate') ? 'warn' : r.status === 'invalid' ? 'danger' : ''}>{r.status}</Badge><span>{r.matches?.[0] ? `${r.matches[0].source_type}: ${r.matches[0].name} (${r.matches[0].confidence}%)` : '—'}</span></div>)}</div></section>; }
function ImportHistory({ rows }) { return <section className="panel"><h2>Import History</h2>{rows.length ? <div className="table"><div className="thead"><span>Date</span><span>File</span><span>Rows</span><span>Imported</span><span>Status</span></div>{rows.map((r) => <div className="tr five" key={r.id}><span>{dateLabel(r.created_at)}</span><span>{r.filename}</span><span>{r.row_count}</span><strong>{r.imported_count}</strong><Badge>{r.status}</Badge></div>)}</div> : <Empty title="No imports yet">CSV imports will appear here with row counts, duplicate counts and matched counts.</Empty>}</section>; }
function ReviewQueue({ rows, acceptMatch }) { return <section className="panel"><h2>Reconciliation Review Queue</h2>{rows.length ? <div className="table"><div className="thead"><span>Date</span><span>Transaction</span><span>Match</span><span>Variance</span><span>Action</span></div>{rows.map((r) => <div className="tr five" key={r.id}><span>{dateLabel(r.transaction_date)}</span><span>{r.description}<small>{money(r.amount)}</small></span><span>{r.source_type} #{r.source_id}<small>{r.confidence}% confidence</small></span><strong className={amountClass(r.variance)}>{money(r.variance)}</strong><button onClick={() => acceptMatch(r.id)}>Accept match</button></div>)}</div> : <Empty title="Nothing needs review">Suggested matches and low-confidence reconciliations appear here.</Empty>}</section>; }
function ForecastPanel({ forecast }) { return <section className="panel"><h2>Forecast / Calendar impact</h2>{forecast?.timeline?.length ? <div className="table"><div className="thead"><span>Date</span><span>Item</span><span>Amount</span><span>Balance</span></div>{forecast.timeline.slice(0, 20).map((r, i) => <div className="tr" key={i}><span>{dateLabel(r.date)}</span><span>{r.name}<small>{r.category}</small></span><strong className={amountClass(r.amount)}>{money(r.amount)}</strong><strong>{money(r.forecast_balance)}</strong></div>)}</div> : <Empty title="No forecast data">Add records or import transactions to update the forecast.</Empty>}</section>; }
